[font]
builtin_box_drawing = true
size = 9.0

[font.normal]
family = "MesloLGM Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control"

[window]
dynamic_padding = true
opacity = 0.85

[window.padding]
x = 16
y = 16

[colors.primary]
background	=	'#000000'
foreground	=	'#FFFFFF'

[colors.normal]
black	=	'#000000'
blue	=	'#3476FF'
cyan	=	'#4483AA'
green	=	'#25A45C'
magenta	=	'#7A82DA'
red		=	'#FC2F52'
white	=	'#CDD4E0'
yellow	=	'#FF936A'

[colors.bright]
black	=	'#000000'
blue	=	'#10B1FE'
cyan	=	'#5FB9BC'
green	=	'#3FC56B'
magenta	=	'#FF78F8'
red		=	'#FF6480'
white	=	'#FFFFFF'
yellow	=	'#F9C859'
